/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/owd/srv/CalibrateJoints.srv
 *
 */


#ifndef OWD_MESSAGE_CALIBRATEJOINTS_H
#define OWD_MESSAGE_CALIBRATEJOINTS_H

#include <ros/service_traits.h>


#include <owd/CalibrateJointsRequest.h>
#include <owd/CalibrateJointsResponse.h>


namespace owd
{

struct CalibrateJoints
{

typedef CalibrateJointsRequest Request;
typedef CalibrateJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalibrateJoints
} // namespace owd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::owd::CalibrateJoints > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::owd::CalibrateJoints&) { return value(); }
};

template<>
struct DataType< ::owd::CalibrateJoints > {
  static const char* value()
  {
    return "owd/CalibrateJoints";
  }

  static const char* value(const ::owd::CalibrateJoints&) { return value(); }
};


// service_traits::MD5Sum< ::owd::CalibrateJointsRequest> should match 
// service_traits::MD5Sum< ::owd::CalibrateJoints > 
template<>
struct MD5Sum< ::owd::CalibrateJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::owd::CalibrateJoints >::value();
  }
  static const char* value(const ::owd::CalibrateJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::owd::CalibrateJointsRequest> should match 
// service_traits::DataType< ::owd::CalibrateJoints > 
template<>
struct DataType< ::owd::CalibrateJointsRequest>
{
  static const char* value()
  {
    return DataType< ::owd::CalibrateJoints >::value();
  }
  static const char* value(const ::owd::CalibrateJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::owd::CalibrateJointsResponse> should match 
// service_traits::MD5Sum< ::owd::CalibrateJoints > 
template<>
struct MD5Sum< ::owd::CalibrateJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::owd::CalibrateJoints >::value();
  }
  static const char* value(const ::owd::CalibrateJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::owd::CalibrateJointsResponse> should match 
// service_traits::DataType< ::owd::CalibrateJoints > 
template<>
struct DataType< ::owd::CalibrateJointsResponse>
{
  static const char* value()
  {
    return DataType< ::owd::CalibrateJoints >::value();
  }
  static const char* value(const ::owd::CalibrateJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MESSAGE_CALIBRATEJOINTS_H
