/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/owd/srv/SetGains.srv
 *
 */


#ifndef OWD_MESSAGE_SETGAINS_H
#define OWD_MESSAGE_SETGAINS_H

#include <ros/service_traits.h>


#include <owd/SetGainsRequest.h>
#include <owd/SetGainsResponse.h>


namespace owd
{

struct SetGains
{

typedef SetGainsRequest Request;
typedef SetGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGains
} // namespace owd


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::owd::SetGains > {
  static const char* value()
  {
    return "8e1b236ea8d7f7d7cef0473991af0ae8";
  }

  static const char* value(const ::owd::SetGains&) { return value(); }
};

template<>
struct DataType< ::owd::SetGains > {
  static const char* value()
  {
    return "owd/SetGains";
  }

  static const char* value(const ::owd::SetGains&) { return value(); }
};


// service_traits::MD5Sum< ::owd::SetGainsRequest> should match 
// service_traits::MD5Sum< ::owd::SetGains > 
template<>
struct MD5Sum< ::owd::SetGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::owd::SetGains >::value();
  }
  static const char* value(const ::owd::SetGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::owd::SetGainsRequest> should match 
// service_traits::DataType< ::owd::SetGains > 
template<>
struct DataType< ::owd::SetGainsRequest>
{
  static const char* value()
  {
    return DataType< ::owd::SetGains >::value();
  }
  static const char* value(const ::owd::SetGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::owd::SetGainsResponse> should match 
// service_traits::MD5Sum< ::owd::SetGains > 
template<>
struct MD5Sum< ::owd::SetGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::owd::SetGains >::value();
  }
  static const char* value(const ::owd::SetGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::owd::SetGainsResponse> should match 
// service_traits::DataType< ::owd::SetGains > 
template<>
struct DataType< ::owd::SetGainsResponse>
{
  static const char* value()
  {
    return DataType< ::owd::SetGains >::value();
  }
  static const char* value(const ::owd::SetGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OWD_MESSAGE_SETGAINS_H
