/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/owd/srv/SetGains.srv
 *
 */


#ifndef OWD_MESSAGE_SETGAINSREQUEST_H
#define OWD_MESSAGE_SETGAINSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pr_msgs/PIDgains.h>

namespace owd
{
template <class ContainerAllocator>
struct SetGainsRequest_
{
  typedef SetGainsRequest_<ContainerAllocator> Type;

  SetGainsRequest_()
    : joint(0)
    , gains()  {
    }
  SetGainsRequest_(const ContainerAllocator& _alloc)
    : joint(0)
    , gains(_alloc)  {
    }



   typedef uint8_t _joint_type;
  _joint_type joint;

   typedef  ::pr_msgs::PIDgains_<ContainerAllocator>  _gains_type;
  _gains_type gains;




  typedef boost::shared_ptr< ::owd::SetGainsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::owd::SetGainsRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SetGainsRequest_

typedef ::owd::SetGainsRequest_<std::allocator<void> > SetGainsRequest;

typedef boost::shared_ptr< ::owd::SetGainsRequest > SetGainsRequestPtr;
typedef boost::shared_ptr< ::owd::SetGainsRequest const> SetGainsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::owd::SetGainsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::owd::SetGainsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace owd

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::owd::SetGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::owd::SetGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::owd::SetGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::owd::SetGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::owd::SetGainsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::owd::SetGainsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::owd::SetGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e1b236ea8d7f7d7cef0473991af0ae8";
  }

  static const char* value(const ::owd::SetGainsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e1b236ea8d7f7d7ULL;
  static const uint64_t static_value2 = 0xcef0473991af0ae8ULL;
};

template<class ContainerAllocator>
struct DataType< ::owd::SetGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "owd/SetGainsRequest";
  }

  static const char* value(const ::owd::SetGainsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::owd::SetGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 joint\n\
pr_msgs/PIDgains gains\n\
\n\
================================================================================\n\
MSG: pr_msgs/PIDgains\n\
float64 kp\n\
float64 kd\n\
float64 ki\n\
";
  }

  static const char* value(const ::owd::SetGainsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::owd::SetGainsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint);
      stream.next(m.gains);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SetGainsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::owd::SetGainsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::owd::SetGainsRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint);
    s << indent << "gains: ";
    s << std::endl;
    Printer< ::pr_msgs::PIDgains_<ContainerAllocator> >::stream(s, indent + "  ", v.gains);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OWD_MESSAGE_SETGAINSREQUEST_H
