(cl:defpackage graspit_msgs-srv
  (:use )
  (:export
   "ANALYZEPOSE"
   "<ANALYZEPOSE-REQUEST>"
   "ANALYZEPOSE-REQUEST"
   "<ANALYZEPOSE-RESPONSE>"
   "ANALYZEPOSE-RESPONSE"
   "GETOBJECTINFO"
   "<GETOBJECTINFO-REQUEST>"
   "GETOBJECTINFO-REQUEST"
   "<GETOBJECTINFO-RESPONSE>"
   "GETOBJECTINFO-RESPONSE"
  ))

