/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pose_msgs/srv/GetPoses.srv
 *
 */


#ifndef POSE_MSGS_MESSAGE_GETPOSESRESPONSE_H
#define POSE_MSGS_MESSAGE_GETPOSESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pose_msgs/Transforms.h>

namespace pose_msgs
{
template <class ContainerAllocator>
struct GetPosesResponse_
{
  typedef GetPosesResponse_<ContainerAllocator> Type;

  GetPosesResponse_()
    : transforms()  {
    }
  GetPosesResponse_(const ContainerAllocator& _alloc)
    : transforms(_alloc)  {
    }



   typedef  ::pose_msgs::Transforms_<ContainerAllocator>  _transforms_type;
  _transforms_type transforms;




  typedef boost::shared_ptr< ::pose_msgs::GetPosesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_msgs::GetPosesResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct GetPosesResponse_

typedef ::pose_msgs::GetPosesResponse_<std::allocator<void> > GetPosesResponse;

typedef boost::shared_ptr< ::pose_msgs::GetPosesResponse > GetPosesResponsePtr;
typedef boost::shared_ptr< ::pose_msgs::GetPosesResponse const> GetPosesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_msgs::GetPosesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pose_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pose_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pose_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_msgs::GetPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_msgs::GetPosesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_msgs::GetPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "61741a788bceb5729711c080d587cc52";
  }

  static const char* value(const ::pose_msgs::GetPosesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x61741a788bceb572ULL;
  static const uint64_t static_value2 = 0x9711c080d587cc52ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_msgs/GetPosesResponse";
  }

  static const char* value(const ::pose_msgs::GetPosesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_msgs/Transforms transforms\n\
\n\
================================================================================\n\
MSG: pose_msgs/Transforms\n\
# This represents a transormation message\n\
Header header\n\
pose_msgs/Transform[] transforms\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: pose_msgs/Transform\n\
# This represents a transormation message\n\
\n\
time time\n\
string frameSrc\n\
string frameDes\n\
geometry_msgs/Vector3 translation\n\
geometry_msgs/Vector3 rotation\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::pose_msgs::GetPosesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.transforms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GetPosesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_msgs::GetPosesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_msgs::GetPosesResponse_<ContainerAllocator>& v)
  {
    s << indent << "transforms: ";
    s << std::endl;
    Printer< ::pose_msgs::Transforms_<ContainerAllocator> >::stream(s, indent + "  ", v.transforms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_MSGS_MESSAGE_GETPOSESRESPONSE_H
