"""autogenerated by genpy from staubli_tx60/SetCartesianGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import staubli_tx60.msg

class SetCartesianGoal(genpy.Message):
  _md5sum = "79c90bebaffd9fd20148254b2ef3ffad"
  _type = "staubli_tx60/SetCartesianGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
StaubliMovementParams params
float64 x
float64 y
float64 z
float64 rx
float64 ry
float64 rz
int32   lineCtrl

================================================================================
MSG: staubli_tx60/StaubliMovementParams
int32 movementType
float64 distBlendPrev #meters unused right now - default .05
float64 distBlendNext #meters unused right now - default .05
float64 jointVelocity #0-1
float64 jointAcc #0-1
float64 jointDec #0-1
float64 endEffectorMaxTranslationVel #meters/sec?
float64 endEffectorMaxRotationalVel #radians/sec



"""
  __slots__ = ['params','x','y','z','rx','ry','rz','lineCtrl']
  _slot_types = ['staubli_tx60/StaubliMovementParams','float64','float64','float64','float64','float64','float64','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       params,x,y,z,rx,ry,rz,lineCtrl

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetCartesianGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.params is None:
        self.params = staubli_tx60.msg.StaubliMovementParams()
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.rx is None:
        self.rx = 0.
      if self.ry is None:
        self.ry = 0.
      if self.rz is None:
        self.rz = 0.
      if self.lineCtrl is None:
        self.lineCtrl = 0
    else:
      self.params = staubli_tx60.msg.StaubliMovementParams()
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.rx = 0.
      self.ry = 0.
      self.rz = 0.
      self.lineCtrl = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i13di.pack(_x.params.movementType, _x.params.distBlendPrev, _x.params.distBlendNext, _x.params.jointVelocity, _x.params.jointAcc, _x.params.jointDec, _x.params.endEffectorMaxTranslationVel, _x.params.endEffectorMaxRotationalVel, _x.x, _x.y, _x.z, _x.rx, _x.ry, _x.rz, _x.lineCtrl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.params is None:
        self.params = staubli_tx60.msg.StaubliMovementParams()
      end = 0
      _x = self
      start = end
      end += 112
      (_x.params.movementType, _x.params.distBlendPrev, _x.params.distBlendNext, _x.params.jointVelocity, _x.params.jointAcc, _x.params.jointDec, _x.params.endEffectorMaxTranslationVel, _x.params.endEffectorMaxRotationalVel, _x.x, _x.y, _x.z, _x.rx, _x.ry, _x.rz, _x.lineCtrl,) = _struct_i13di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i13di.pack(_x.params.movementType, _x.params.distBlendPrev, _x.params.distBlendNext, _x.params.jointVelocity, _x.params.jointAcc, _x.params.jointDec, _x.params.endEffectorMaxTranslationVel, _x.params.endEffectorMaxRotationalVel, _x.x, _x.y, _x.z, _x.rx, _x.ry, _x.rz, _x.lineCtrl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.params is None:
        self.params = staubli_tx60.msg.StaubliMovementParams()
      end = 0
      _x = self
      start = end
      end += 112
      (_x.params.movementType, _x.params.distBlendPrev, _x.params.distBlendNext, _x.params.jointVelocity, _x.params.jointAcc, _x.params.jointDec, _x.params.endEffectorMaxTranslationVel, _x.params.endEffectorMaxRotationalVel, _x.x, _x.y, _x.z, _x.rx, _x.ry, _x.rz, _x.lineCtrl,) = _struct_i13di.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i13di = struct.Struct("<i13di")
