/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/srv/AddPrecomputedTrajectory.srv
 *
 */


#ifndef PR_MSGS_MESSAGE_ADDPRECOMPUTEDTRAJECTORYREQUEST_H
#define PR_MSGS_MESSAGE_ADDPRECOMPUTEDTRAJECTORYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pr_msgs/WAMPrecomputedBlendedTrajectory.h>

namespace pr_msgs
{
template <class ContainerAllocator>
struct AddPrecomputedTrajectoryRequest_
{
  typedef AddPrecomputedTrajectoryRequest_<ContainerAllocator> Type;

  AddPrecomputedTrajectoryRequest_()
    : traj()  {
    }
  AddPrecomputedTrajectoryRequest_(const ContainerAllocator& _alloc)
    : traj(_alloc)  {
    }



   typedef  ::pr_msgs::WAMPrecomputedBlendedTrajectory_<ContainerAllocator>  _traj_type;
  _traj_type traj;




  typedef boost::shared_ptr< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct AddPrecomputedTrajectoryRequest_

typedef ::pr_msgs::AddPrecomputedTrajectoryRequest_<std::allocator<void> > AddPrecomputedTrajectoryRequest;

typedef boost::shared_ptr< ::pr_msgs::AddPrecomputedTrajectoryRequest > AddPrecomputedTrajectoryRequestPtr;
typedef boost::shared_ptr< ::pr_msgs::AddPrecomputedTrajectoryRequest const> AddPrecomputedTrajectoryRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75e7d5e1c8aabc62097ff8b39b0402be";
  }

  static const char* value(const ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75e7d5e1c8aabc62ULL;
  static const uint64_t static_value2 = 0x097ff8b39b0402beULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/AddPrecomputedTrajectoryRequest";
  }

  static const char* value(const ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/WAMPrecomputedBlendedTrajectory traj\n\
\n\
================================================================================\n\
MSG: pr_msgs/WAMPrecomputedBlendedTrajectory\n\
int16 id\n\
bool HoldOnStall\n\
bool WaitForStart\n\
pr_msgs/Joints start_position\n\
pr_msgs/Joints end_position\n\
pr_msgs/Joints max_joint_vel\n\
pr_msgs/Joints max_joint_accel\n\
pr_msgs/WAMPrecomputedBlendElement[] macpieces\n\
float64 traj_duration\n\
\n\
================================================================================\n\
MSG: pr_msgs/Joints\n\
float64[] j\n\
\n\
================================================================================\n\
MSG: pr_msgs/WAMPrecomputedBlendElement\n\
pr_msgs/Joints start_pos\n\
pr_msgs/Joints end_pos\n\
float64 start_time\n\
float64 duration\n\
float64 max_path_velocity\n\
float64 max_path_acceleration\n\
";
  }

  static const char* value(const ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AddPrecomputedTrajectoryRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_msgs::AddPrecomputedTrajectoryRequest_<ContainerAllocator>& v)
  {
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::pr_msgs::WAMPrecomputedBlendedTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_ADDPRECOMPUTEDTRAJECTORYREQUEST_H
