/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/srv/ArmConfigCheck.srv
 *
 */


#ifndef PR_MSGS_MESSAGE_ARMCONFIGCHECKRESPONSE_H
#define PR_MSGS_MESSAGE_ARMCONFIGCHECKRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr_msgs
{
template <class ContainerAllocator>
struct ArmConfigCheckResponse_
{
  typedef ArmConfigCheckResponse_<ContainerAllocator> Type;

  ArmConfigCheckResponse_()
    : current_self_collision(false)
    , current_env_collision(false)
    , future_self_collision(false)
    , future_env_collision(false)
    , current_joint_limits_exceeded(false)
    , future_joint_limits_exceeded(false)  {
    }
  ArmConfigCheckResponse_(const ContainerAllocator& _alloc)
    : current_self_collision(false)
    , current_env_collision(false)
    , future_self_collision(false)
    , future_env_collision(false)
    , current_joint_limits_exceeded(false)
    , future_joint_limits_exceeded(false)  {
    }



   typedef uint8_t _current_self_collision_type;
  _current_self_collision_type current_self_collision;

   typedef uint8_t _current_env_collision_type;
  _current_env_collision_type current_env_collision;

   typedef uint8_t _future_self_collision_type;
  _future_self_collision_type future_self_collision;

   typedef uint8_t _future_env_collision_type;
  _future_env_collision_type future_env_collision;

   typedef uint8_t _current_joint_limits_exceeded_type;
  _current_joint_limits_exceeded_type current_joint_limits_exceeded;

   typedef uint8_t _future_joint_limits_exceeded_type;
  _future_joint_limits_exceeded_type future_joint_limits_exceeded;




  typedef boost::shared_ptr< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct ArmConfigCheckResponse_

typedef ::pr_msgs::ArmConfigCheckResponse_<std::allocator<void> > ArmConfigCheckResponse;

typedef boost::shared_ptr< ::pr_msgs::ArmConfigCheckResponse > ArmConfigCheckResponsePtr;
typedef boost::shared_ptr< ::pr_msgs::ArmConfigCheckResponse const> ArmConfigCheckResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27773a29cfec7a99cc44eea74da93860";
  }

  static const char* value(const ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27773a29cfec7a99ULL;
  static const uint64_t static_value2 = 0xcc44eea74da93860ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/ArmConfigCheckResponse";
  }

  static const char* value(const ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool current_self_collision\n\
bool current_env_collision\n\
bool future_self_collision\n\
bool future_env_collision\n\
\n\
bool current_joint_limits_exceeded\n\
bool future_joint_limits_exceeded\n\
\n\
";
  }

  static const char* value(const ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_self_collision);
      stream.next(m.current_env_collision);
      stream.next(m.future_self_collision);
      stream.next(m.future_env_collision);
      stream.next(m.current_joint_limits_exceeded);
      stream.next(m.future_joint_limits_exceeded);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ArmConfigCheckResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_msgs::ArmConfigCheckResponse_<ContainerAllocator>& v)
  {
    s << indent << "current_self_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_self_collision);
    s << indent << "current_env_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_env_collision);
    s << indent << "future_self_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.future_self_collision);
    s << indent << "future_env_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.future_env_collision);
    s << indent << "current_joint_limits_exceeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_joint_limits_exceeded);
    s << indent << "future_joint_limits_exceeded: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.future_joint_limits_exceeded);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_ARMCONFIGCHECKRESPONSE_H
