/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg/BHTactile.msg
 *
 */


#ifndef PR_MSGS_MESSAGE_BHTACTILE_H
#define PR_MSGS_MESSAGE_BHTACTILE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr_msgs
{
template <class ContainerAllocator>
struct BHTactile_
{
  typedef BHTactile_<ContainerAllocator> Type;

  BHTactile_()
    : finger1()
    , finger2()
    , finger3()
    , palm()  {
    }
  BHTactile_(const ContainerAllocator& _alloc)
    : finger1(_alloc)
    , finger2(_alloc)
    , finger3(_alloc)
    , palm(_alloc)  {
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _finger1_type;
  _finger1_type finger1;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _finger2_type;
  _finger2_type finger2;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _finger3_type;
  _finger3_type finger3;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _palm_type;
  _palm_type palm;




  typedef boost::shared_ptr< ::pr_msgs::BHTactile_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::BHTactile_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct BHTactile_

typedef ::pr_msgs::BHTactile_<std::allocator<void> > BHTactile;

typedef boost::shared_ptr< ::pr_msgs::BHTactile > BHTactilePtr;
typedef boost::shared_ptr< ::pr_msgs::BHTactile const> BHTactileConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_msgs::BHTactile_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_msgs::BHTactile_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::BHTactile_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::BHTactile_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::BHTactile_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::BHTactile_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::BHTactile_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::BHTactile_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::BHTactile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f40a82aa99391835587004e5c16d74c4";
  }

  static const char* value(const ::pr_msgs::BHTactile_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf40a82aa99391835ULL;
  static const uint64_t static_value2 = 0x587004e5c16d74c4ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::BHTactile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/BHTactile";
  }

  static const char* value(const ::pr_msgs::BHTactile_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::BHTactile_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] finger1\n\
float32[] finger2\n\
float32[] finger3\n\
float32[] palm\n\
";
  }

  static const char* value(const ::pr_msgs::BHTactile_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_msgs::BHTactile_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finger1);
      stream.next(m.finger2);
      stream.next(m.finger3);
      stream.next(m.palm);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BHTactile_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::BHTactile_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_msgs::BHTactile_<ContainerAllocator>& v)
  {
    s << indent << "finger1[]" << std::endl;
    for (size_t i = 0; i < v.finger1.size(); ++i)
    {
      s << indent << "  finger1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.finger1[i]);
    }
    s << indent << "finger2[]" << std::endl;
    for (size_t i = 0; i < v.finger2.size(); ++i)
    {
      s << indent << "  finger2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.finger2[i]);
    }
    s << indent << "finger3[]" << std::endl;
    for (size_t i = 0; i < v.finger3.size(); ++i)
    {
      s << indent << "  finger3[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.finger3[i]);
    }
    s << indent << "palm[]" << std::endl;
    for (size_t i = 0; i < v.palm.size(); ++i)
    {
      s << indent << "  palm[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.palm[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_BHTACTILE_H
