/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg/OccGrid3D.msg
 *
 */


#ifndef PR_MSGS_MESSAGE_OCCGRID3D_H
#define PR_MSGS_MESSAGE_OCCGRID3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point32.h>

namespace pr_msgs
{
template <class ContainerAllocator>
struct OccGrid3D_
{
  typedef OccGrid3D_<ContainerAllocator> Type;

  OccGrid3D_()
    : header()
    , resolution(0.0)
    , num_x_voxels(0)
    , num_y_voxels(0)
    , num_z_voxels(0)
    , origin()
    , data()  {
    }
  OccGrid3D_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , resolution(0.0)
    , num_x_voxels(0)
    , num_y_voxels(0)
    , num_z_voxels(0)
    , origin(_alloc)
    , data(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _resolution_type;
  _resolution_type resolution;

   typedef uint32_t _num_x_voxels_type;
  _num_x_voxels_type num_x_voxels;

   typedef uint32_t _num_y_voxels_type;
  _num_y_voxels_type num_y_voxels;

   typedef uint32_t _num_z_voxels_type;
  _num_z_voxels_type num_z_voxels;

   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::pr_msgs::OccGrid3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::OccGrid3D_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct OccGrid3D_

typedef ::pr_msgs::OccGrid3D_<std::allocator<void> > OccGrid3D;

typedef boost::shared_ptr< ::pr_msgs::OccGrid3D > OccGrid3DPtr;
typedef boost::shared_ptr< ::pr_msgs::OccGrid3D const> OccGrid3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_msgs::OccGrid3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_msgs::OccGrid3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::OccGrid3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::OccGrid3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::OccGrid3D_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c71e0896dd3dc42f5341886fcc48fd1";
  }

  static const char* value(const ::pr_msgs::OccGrid3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c71e0896dd3dc42ULL;
  static const uint64_t static_value2 = 0xf5341886fcc48fd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/OccGrid3D";
  }

  static const char* value(const ::pr_msgs::OccGrid3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#a 3-D grid map, modeled after the OccGrid.msg type\n\
Header header\n\
\n\
#resolution of cells [m/side] \n\
float32 resolution\n\
\n\
# num cells in {x,y,z} direction\n\
uint32 num_x_voxels\n\
uint32 num_y_voxels\n\
uint32 num_z_voxels\n\
\n\
# exact center of map (always an odd number of voxels in each dimension)\n\
geometry_msgs/Point32 origin\n\
\n\
# the map data. 0-100, representing probability: ceil(100*p_occupied-0.5)\n\
# index =  kk * num_y_voxels * num_x_voxels + jj * num_x_voxels + ii\n\
byte[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::pr_msgs::OccGrid3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.resolution);
      stream.next(m.num_x_voxels);
      stream.next(m.num_y_voxels);
      stream.next(m.num_z_voxels);
      stream.next(m.origin);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct OccGrid3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::OccGrid3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_msgs::OccGrid3D_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "resolution: ";
    Printer<float>::stream(s, indent + "  ", v.resolution);
    s << indent << "num_x_voxels: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_x_voxels);
    s << indent << "num_y_voxels: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_y_voxels);
    s << indent << "num_z_voxels: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.num_z_voxels);
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_OCCGRID3D_H
