/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg/PixelCoordinateList.msg
 *
 */


#ifndef PR_MSGS_MESSAGE_PIXELCOORDINATELIST_H
#define PR_MSGS_MESSAGE_PIXELCOORDINATELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <pr_msgs/PixelCoordinate.h>

namespace pr_msgs
{
template <class ContainerAllocator>
struct PixelCoordinateList_
{
  typedef PixelCoordinateList_<ContainerAllocator> Type;

  PixelCoordinateList_()
    : header()
    , coordinates()
    , originalTimeStamp()  {
    }
  PixelCoordinateList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , coordinates(_alloc)
    , originalTimeStamp()  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::pr_msgs::PixelCoordinate_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::pr_msgs::PixelCoordinate_<ContainerAllocator> >::other >  _coordinates_type;
  _coordinates_type coordinates;

   typedef ros::Time _originalTimeStamp_type;
  _originalTimeStamp_type originalTimeStamp;




  typedef boost::shared_ptr< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct PixelCoordinateList_

typedef ::pr_msgs::PixelCoordinateList_<std::allocator<void> > PixelCoordinateList;

typedef boost::shared_ptr< ::pr_msgs::PixelCoordinateList > PixelCoordinateListPtr;
typedef boost::shared_ptr< ::pr_msgs::PixelCoordinateList const> PixelCoordinateListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_msgs::PixelCoordinateList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c9bc0eadac36ef3a77fd4cd41e78c02";
  }

  static const char* value(const ::pr_msgs::PixelCoordinateList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c9bc0eadac36ef3ULL;
  static const uint64_t static_value2 = 0xa77fd4cd41e78c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/PixelCoordinateList";
  }

  static const char* value(const ::pr_msgs::PixelCoordinateList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
PixelCoordinate[] coordinates\n\
\n\
time originalTimeStamp\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: pr_msgs/PixelCoordinate\n\
int16 x\n\
int16 y\n\
";
  }

  static const char* value(const ::pr_msgs::PixelCoordinateList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.coordinates);
      stream.next(m.originalTimeStamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PixelCoordinateList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::PixelCoordinateList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_msgs::PixelCoordinateList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "coordinates[]" << std::endl;
    for (size_t i = 0; i < v.coordinates.size(); ++i)
    {
      s << indent << "  coordinates[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pr_msgs::PixelCoordinate_<ContainerAllocator> >::stream(s, indent + "    ", v.coordinates[i]);
    }
    s << indent << "originalTimeStamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.originalTimeStamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_PIXELCOORDINATELIST_H
