/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg/TrajInfo.msg
 *
 */


#ifndef PR_MSGS_MESSAGE_TRAJINFO_H
#define PR_MSGS_MESSAGE_TRAJINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pr_msgs
{
template <class ContainerAllocator>
struct TrajInfo_
{
  typedef TrajInfo_<ContainerAllocator> Type;

  TrajInfo_()
    : id(0)
    , type()
    , end_position()
    , state(0)  {
    }
  TrajInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , type(_alloc)
    , end_position(_alloc)
    , state(0)  {
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _end_position_type;
  _end_position_type end_position;

   typedef uint32_t _state_type;
  _state_type state;


    enum { state_pending = 0 };
     enum { state_active = 1 };
     enum { state_done = 3 };
     enum { state_aborted = 4 };
     enum { state_running = 1 };
     enum { state_paused = 2 };
 

  typedef boost::shared_ptr< ::pr_msgs::TrajInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pr_msgs::TrajInfo_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct TrajInfo_

typedef ::pr_msgs::TrajInfo_<std::allocator<void> > TrajInfo;

typedef boost::shared_ptr< ::pr_msgs::TrajInfo > TrajInfoPtr;
typedef boost::shared_ptr< ::pr_msgs::TrajInfo const> TrajInfoConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pr_msgs::TrajInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pr_msgs::TrajInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pr_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pr_msgs': ['/home/mpcadosch/Dev/bci_ros/bci_project_ws/src/pr_msgs/msg', '/home/mpcadosch/Dev/bci_ros/bci_project_ws/devel/share/pr_msgs/msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::TrajInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pr_msgs::TrajInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::TrajInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pr_msgs::TrajInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::TrajInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pr_msgs::TrajInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pr_msgs::TrajInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82f4530e5ffe77991769af4f85589db5";
  }

  static const char* value(const ::pr_msgs::TrajInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82f4530e5ffe7799ULL;
  static const uint64_t static_value2 = 0x1769af4f85589db5ULL;
};

template<class ContainerAllocator>
struct DataType< ::pr_msgs::TrajInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pr_msgs/TrajInfo";
  }

  static const char* value(const ::pr_msgs::TrajInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pr_msgs::TrajInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
string type\n\
float64[] end_position\n\
uint32 state\n\
\n\
uint8 state_pending=0\n\
uint8 state_active=1\n\
uint8 state_done=3\n\
uint8 state_aborted=4\n\
\n\
# Deprecated state names; please use the ones above\n\
uint8 state_running=1 # deprecated\n\
uint8 state_paused=2  # deprecated: look for state_traj_paused in WAMState.state\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::pr_msgs::TrajInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pr_msgs::TrajInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.end_position);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct TrajInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pr_msgs::TrajInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pr_msgs::TrajInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "end_position[]" << std::endl;
    for (size_t i = 0; i < v.end_position.size(); ++i)
    {
      s << indent << "  end_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.end_position[i]);
    }
    s << indent << "state: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PR_MSGS_MESSAGE_TRAJINFO_H
