/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/model_rec2/srv/FindObjects.srv
 *
 */


#ifndef MODEL_REC2_MESSAGE_FINDOBJECTS_H
#define MODEL_REC2_MESSAGE_FINDOBJECTS_H

#include <ros/service_traits.h>


#include <model_rec2/FindObjectsRequest.h>
#include <model_rec2/FindObjectsResponse.h>


namespace model_rec2
{

struct FindObjects
{

typedef FindObjectsRequest Request;
typedef FindObjectsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindObjects
} // namespace model_rec2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::model_rec2::FindObjects > {
  static const char* value()
  {
    return "4b18b6673feb7735ef885c0b6572111b";
  }

  static const char* value(const ::model_rec2::FindObjects&) { return value(); }
};

template<>
struct DataType< ::model_rec2::FindObjects > {
  static const char* value()
  {
    return "model_rec2/FindObjects";
  }

  static const char* value(const ::model_rec2::FindObjects&) { return value(); }
};


// service_traits::MD5Sum< ::model_rec2::FindObjectsRequest> should match 
// service_traits::MD5Sum< ::model_rec2::FindObjects > 
template<>
struct MD5Sum< ::model_rec2::FindObjectsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::model_rec2::FindObjects >::value();
  }
  static const char* value(const ::model_rec2::FindObjectsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::model_rec2::FindObjectsRequest> should match 
// service_traits::DataType< ::model_rec2::FindObjects > 
template<>
struct DataType< ::model_rec2::FindObjectsRequest>
{
  static const char* value()
  {
    return DataType< ::model_rec2::FindObjects >::value();
  }
  static const char* value(const ::model_rec2::FindObjectsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::model_rec2::FindObjectsResponse> should match 
// service_traits::MD5Sum< ::model_rec2::FindObjects > 
template<>
struct MD5Sum< ::model_rec2::FindObjectsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::model_rec2::FindObjects >::value();
  }
  static const char* value(const ::model_rec2::FindObjectsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::model_rec2::FindObjectsResponse> should match 
// service_traits::DataType< ::model_rec2::FindObjects > 
template<>
struct DataType< ::model_rec2::FindObjectsResponse>
{
  static const char* value()
  {
    return DataType< ::model_rec2::FindObjects >::value();
  }
  static const char* value(const ::model_rec2::FindObjectsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODEL_REC2_MESSAGE_FINDOBJECTS_H
