/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/staubli_tx60/srv/FwdKinematics.srv
 *
 */


#ifndef STAUBLI_TX60_MESSAGE_FWDKINEMATICS_H
#define STAUBLI_TX60_MESSAGE_FWDKINEMATICS_H

#include <ros/service_traits.h>


#include <staubli_tx60/FwdKinematicsRequest.h>
#include <staubli_tx60/FwdKinematicsResponse.h>


namespace staubli_tx60
{

struct FwdKinematics
{

typedef FwdKinematicsRequest Request;
typedef FwdKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FwdKinematics
} // namespace staubli_tx60


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::staubli_tx60::FwdKinematics > {
  static const char* value()
  {
    return "f0d139f661446e7d7135f7b047802a5c";
  }

  static const char* value(const ::staubli_tx60::FwdKinematics&) { return value(); }
};

template<>
struct DataType< ::staubli_tx60::FwdKinematics > {
  static const char* value()
  {
    return "staubli_tx60/FwdKinematics";
  }

  static const char* value(const ::staubli_tx60::FwdKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::staubli_tx60::FwdKinematicsRequest> should match 
// service_traits::MD5Sum< ::staubli_tx60::FwdKinematics > 
template<>
struct MD5Sum< ::staubli_tx60::FwdKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::staubli_tx60::FwdKinematics >::value();
  }
  static const char* value(const ::staubli_tx60::FwdKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::staubli_tx60::FwdKinematicsRequest> should match 
// service_traits::DataType< ::staubli_tx60::FwdKinematics > 
template<>
struct DataType< ::staubli_tx60::FwdKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::staubli_tx60::FwdKinematics >::value();
  }
  static const char* value(const ::staubli_tx60::FwdKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::staubli_tx60::FwdKinematicsResponse> should match 
// service_traits::MD5Sum< ::staubli_tx60::FwdKinematics > 
template<>
struct MD5Sum< ::staubli_tx60::FwdKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::staubli_tx60::FwdKinematics >::value();
  }
  static const char* value(const ::staubli_tx60::FwdKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::staubli_tx60::FwdKinematicsResponse> should match 
// service_traits::DataType< ::staubli_tx60::FwdKinematics > 
template<>
struct DataType< ::staubli_tx60::FwdKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::staubli_tx60::FwdKinematics >::value();
  }
  static const char* value(const ::staubli_tx60::FwdKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STAUBLI_TX60_MESSAGE_FWDKINEMATICS_H
