(cl:in-package staubli_tx60-msg)
(cl:export '(MOVEMENTTYPE-VAL
          MOVEMENTTYPE
          DISTBLENDPREV-VAL
          DISTBLENDPREV
          DISTBLENDNEXT-VAL
          DISTBLENDNEXT
          JOINTVELOCITY-VAL
          JOINTVELOCITY
          JOINTACC-VAL
          JOINTACC
          JOINTDEC-VAL
          JOINTDEC
          ENDEFFECTORMAXTRANSLATIONVEL-VAL
          ENDEFFECTORMAXTRANSLATIONVEL
          ENDEFFECTORMAXROTATIONALVEL-VAL
          ENDEFFECTORMAXROTATIONALVEL
))