; Auto-generated. Do not edit!


(cl:in-package staubli_tx60-msg)


;//! \htmlinclude SetJointTrajectoryGoal.msg.html

(cl:defclass <SetJointTrajectoryGoal> (roslisp-msg-protocol:ros-message)
  ((jointTrajectory
    :reader jointTrajectory
    :initarg :jointTrajectory
    :type (cl:vector staubli_tx60-msg:JointTrajectoryPoint)
   :initform (cl:make-array 0 :element-type 'staubli_tx60-msg:JointTrajectoryPoint :initial-element (cl:make-instance 'staubli_tx60-msg:JointTrajectoryPoint))))
)

(cl:defclass SetJointTrajectoryGoal (<SetJointTrajectoryGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetJointTrajectoryGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetJointTrajectoryGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name staubli_tx60-msg:<SetJointTrajectoryGoal> is deprecated: use staubli_tx60-msg:SetJointTrajectoryGoal instead.")))

(cl:ensure-generic-function 'jointTrajectory-val :lambda-list '(m))
(cl:defmethod jointTrajectory-val ((m <SetJointTrajectoryGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader staubli_tx60-msg:jointTrajectory-val is deprecated.  Use staubli_tx60-msg:jointTrajectory instead.")
  (jointTrajectory m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetJointTrajectoryGoal>) ostream)
  "Serializes a message object of type '<SetJointTrajectoryGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'jointTrajectory))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'jointTrajectory))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetJointTrajectoryGoal>) istream)
  "Deserializes a message object of type '<SetJointTrajectoryGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'jointTrajectory) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'jointTrajectory)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'staubli_tx60-msg:JointTrajectoryPoint))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetJointTrajectoryGoal>)))
  "Returns string type for a message object of type '<SetJointTrajectoryGoal>"
  "staubli_tx60/SetJointTrajectoryGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetJointTrajectoryGoal)))
  "Returns string type for a message object of type 'SetJointTrajectoryGoal"
  "staubli_tx60/SetJointTrajectoryGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetJointTrajectoryGoal>)))
  "Returns md5sum for a message object of type '<SetJointTrajectoryGoal>"
  "6cf908dc35c4586beaf79d9cb61401d8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetJointTrajectoryGoal)))
  "Returns md5sum for a message object of type 'SetJointTrajectoryGoal"
  "6cf908dc35c4586beaf79d9cb61401d8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetJointTrajectoryGoal>)))
  "Returns full string definition for message of type '<SetJointTrajectoryGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%JointTrajectoryPoint[] jointTrajectory # Points contain joint space goal points and staubli movement params which encode velocity, acceleration, and goal region constraints~%~%================================================================================~%MSG: staubli_tx60/JointTrajectoryPoint~%float64[] jointValues~%StaubliMovementParams params~%================================================================================~%MSG: staubli_tx60/StaubliMovementParams~%int32 movementType~%float64 distBlendPrev #meters unused right now - default .05~%float64 distBlendNext #meters unused right now - default .05~%float64 jointVelocity #0-1~%float64 jointAcc #0-1~%float64 jointDec #0-1~%float64 endEffectorMaxTranslationVel #meters/sec?~%float64 endEffectorMaxRotationalVel #radians/sec~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetJointTrajectoryGoal)))
  "Returns full string definition for message of type 'SetJointTrajectoryGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%JointTrajectoryPoint[] jointTrajectory # Points contain joint space goal points and staubli movement params which encode velocity, acceleration, and goal region constraints~%~%================================================================================~%MSG: staubli_tx60/JointTrajectoryPoint~%float64[] jointValues~%StaubliMovementParams params~%================================================================================~%MSG: staubli_tx60/StaubliMovementParams~%int32 movementType~%float64 distBlendPrev #meters unused right now - default .05~%float64 distBlendNext #meters unused right now - default .05~%float64 jointVelocity #0-1~%float64 jointAcc #0-1~%float64 jointDec #0-1~%float64 endEffectorMaxTranslationVel #meters/sec?~%float64 endEffectorMaxRotationalVel #radians/sec~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetJointTrajectoryGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'jointTrajectory) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetJointTrajectoryGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SetJointTrajectoryGoal
    (cl:cons ':jointTrajectory (jointTrajectory msg))
))
