; Auto-generated. Do not edit!


(cl:in-package staubli_tx60-msg)


;//! \htmlinclude SetJointsFeedback.msg.html

(cl:defclass <SetJointsFeedback> (roslisp-msg-protocol:ros-message)
  ((j
    :reader j
    :initarg :j
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass SetJointsFeedback (<SetJointsFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetJointsFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetJointsFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name staubli_tx60-msg:<SetJointsFeedback> is deprecated: use staubli_tx60-msg:SetJointsFeedback instead.")))

(cl:ensure-generic-function 'j-val :lambda-list '(m))
(cl:defmethod j-val ((m <SetJointsFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader staubli_tx60-msg:j-val is deprecated.  Use staubli_tx60-msg:j instead.")
  (j m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetJointsFeedback>) ostream)
  "Serializes a message object of type '<SetJointsFeedback>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'j))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'j))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetJointsFeedback>) istream)
  "Deserializes a message object of type '<SetJointsFeedback>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'j) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'j)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetJointsFeedback>)))
  "Returns string type for a message object of type '<SetJointsFeedback>"
  "staubli_tx60/SetJointsFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetJointsFeedback)))
  "Returns string type for a message object of type 'SetJointsFeedback"
  "staubli_tx60/SetJointsFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetJointsFeedback>)))
  "Returns md5sum for a message object of type '<SetJointsFeedback>"
  "59542e81b1fd2eaee58892b9055022e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetJointsFeedback)))
  "Returns md5sum for a message object of type 'SetJointsFeedback"
  "59542e81b1fd2eaee58892b9055022e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetJointsFeedback>)))
  "Returns full string definition for message of type '<SetJointsFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] j~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetJointsFeedback)))
  "Returns full string definition for message of type 'SetJointsFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64[] j~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetJointsFeedback>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'j) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetJointsFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetJointsFeedback
    (cl:cons ':j (j msg))
))
