/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mpcadosch/Dev/bci_ros/bci_project_ws/src/graspit_msgs/srv/GetObjectInfo.srv
 *
 */


#ifndef GRASPIT_MSGS_MESSAGE_GETOBJECTINFO_H
#define GRASPIT_MSGS_MESSAGE_GETOBJECTINFO_H

#include <ros/service_traits.h>


#include <graspit_msgs/GetObjectInfoRequest.h>
#include <graspit_msgs/GetObjectInfoResponse.h>


namespace graspit_msgs
{

struct GetObjectInfo
{

typedef GetObjectInfoRequest Request;
typedef GetObjectInfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectInfo
} // namespace graspit_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::graspit_msgs::GetObjectInfo > {
  static const char* value()
  {
    return "bdc8d8269b448089f6ea6aa337b990f2";
  }

  static const char* value(const ::graspit_msgs::GetObjectInfo&) { return value(); }
};

template<>
struct DataType< ::graspit_msgs::GetObjectInfo > {
  static const char* value()
  {
    return "graspit_msgs/GetObjectInfo";
  }

  static const char* value(const ::graspit_msgs::GetObjectInfo&) { return value(); }
};


// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfoRequest> should match 
// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfo > 
template<>
struct MD5Sum< ::graspit_msgs::GetObjectInfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::GetObjectInfoRequest> should match 
// service_traits::DataType< ::graspit_msgs::GetObjectInfo > 
template<>
struct DataType< ::graspit_msgs::GetObjectInfoRequest>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfoResponse> should match 
// service_traits::MD5Sum< ::graspit_msgs::GetObjectInfo > 
template<>
struct MD5Sum< ::graspit_msgs::GetObjectInfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::graspit_msgs::GetObjectInfoResponse> should match 
// service_traits::DataType< ::graspit_msgs::GetObjectInfo > 
template<>
struct DataType< ::graspit_msgs::GetObjectInfoResponse>
{
  static const char* value()
  {
    return DataType< ::graspit_msgs::GetObjectInfo >::value();
  }
  static const char* value(const ::graspit_msgs::GetObjectInfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRASPIT_MSGS_MESSAGE_GETOBJECTINFO_H
